Engine.IO upgrade and fixing things
Automattic/mydb pull request #35
Opened 2023-03-30 13:58 UTC by thedebian

### Summary

This PR updates engine.io and fixes everything that needs to be fixed after update.

It should also validate 
Automattic/mydb-client#34

### Testing
* Apply PR
* `npm install`
* Go to the test folder and `docker-compose up`
* Go back to the root folder and `make test`
* ✅ All tests should pass

2023-04-03 19:05 UTC, jgcaruso requested changes
Code changes look reasonable, left one comment on a change to `on('message'` but I think it might be OK.

Ran into a timeout running tests (made sure I was using node 18 before I ran `npm install`)
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/4081020/229602839-94a82b35-a3e3-4a21-aaa9-62c189ef56c1.png">

the new docker-compose file was running as well 
<img width="911" alt="image" src="https://user-images.githubusercontent.com/4081020/229603063-21282d20-0da0-4de9-94bf-c7caa0f7066d.png">

2023-04-03 19:06 UTC, jgcaruso commented
Separately, I'm curious if you tested this as a dependency installed in all of the containers? Ex rebuild `cloudup` with this new version, or if this PR is just for the changes that get testing working correctly?

2023-04-04 10:39 UTC, thedebian commented on index.js
> -  this.redisSub.on('message', this.onpub.bind(this));
Not sure, I think it's because the thing gets subscribed by the subscription object anyway, but I put it back just in case

2023-04-04 10:40 UTC, thedebian commented on index.js
> -  this.redisSub.on('message', this.onpub.bind(this));
> Ran into a timeout running tests (made sure I was using node 18 before I ran `npm install`)

Did you docker-compose up in the test folder ?

2023-04-04 14:56 UTC, jgcaruso approved these changes
Tests pass after updating the hash in `package-lock`.

Looking good!

2023-04-05 10:12 UTC, merged